"""add service_status table

Revision ID: 501c559998d7
Revises: 750b1f0768b3
Create Date: 2026-07-02 01:34:47.414396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '501c559998d7'
down_revision: Union[str, None] = '750b1f0768b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_status', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_service_status_checked_at', table_name='service_status')
    op.drop_column('service_status', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_status', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index('ix_service_status_checked_at', 'service_status', ['checked_at'], unique=False)
    op.alter_column('service_status', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
